apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-info-service-deployments
  namespace: bozo-book-library-dev
  labels:
    application: bozo-book-library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-info-service
      namespace: bozo-book-library-dev
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: bozobooks-app
        vault.hashicorp.com/agent-inject-secret-config: bozobooks/data/googleapi-config
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "bozobooks/data/googleapi-config" -}}
            export googleapikey="{{ .Data.data.googleapikey }}"
          {{- end }}
      labels:
        app: book-info-service
        namespace: bozo-book-library-dev
    spec:
      serviceAccountName: bozobooks-app
      containers:
        - name: book-info-service
          image: abvijaykumar/bozo-book-info-service:58
          args:
            ['sh', '-c', 'source /vault/secrets/config && ./bookinfoservice -Dquarkus.http.host=0.0.0.0']
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
