apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bozobooks-master-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
    cert-manager.io/cluster-issuer: "bozo-letsencrypt-issuer"
spec:
  tls:
    - hosts:
      - bozobooks.com
      secretName: bozo-letsencrypt-issuer-dev
  rules:
  - host: bozobooks.com

---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: bozobooks-app-ingress
  namespace: bozo-book-library-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: bozobooks.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  book-library-ui-svc
            port: 
              number: 80
      - path: /bookinfo
        pathType: Prefix
        backend:
          service:
            name:  book-info-service-svc
            port: 
              number: 8080
      - path: /booklib
        pathType: Prefix
        backend:
          service:
            name:  book-library-service-svc
            port: 
              number: 8080        
    

---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: bozobooks.com
    http:
      paths:
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name:  argocd-server
            port: 
              number: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: bozobooks.com
    http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-grafana
            port: 
              number: 3000
      - path: /alertmanager
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-kube-prome-alertmanager
            port: 
              number: 9093
      - path: /prom
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-kube-prome-prometheus
            port: 
              number: 9090              

---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: vault-ingress
  namespace: vault
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: bozobooks.com
    http:
      paths:
      - path: /vault
        pathType: Prefix
        backend:
          service:
            name:  vault
            port: 
              number: 8200

